### ISSUE TITLE
Make commands in Results screen case-insensitive

### ISSUE THREAD

**Issue by alesan99** [alesan99/eecs348project#9]
It asks you if you want to input your next expression (Y/N)

Ideally it should accept lowercase y/n as well.

**Comment by Discord-ian** [comment]
Added a line to the function Resultstate::input in 48d557d3782303b6d881ffa964e1a439c8e02a3d
`	std::transform(input.begin(), input.end(), input.begin(), ::tolower);
`

**Comment by Discord-ian** [comment]
We might want to look at also allowing a default if the user enters nothing, denoted as either Y/n or y/N. 
The user can simply enter nothing and press enter, and we will select the default option instead of prompting again for a valid input.
